from enum import Enum

class Topics(Enum):
    ENTERTAINMENT_AND_POP_CULTURE = 1
    GEOGRAPHY_AND_TRAVEL = 2
    HEALTH_AND_MEDICINE = 3
    LIFESTYLES_AND_SOCIAL_ISSUES = 4
    LITERATURE = 5
    PHILOSOHY_AND_RELIGION = 6
    POLITICS = 7
    LAW_AND_GOVERNMENT = 8
    SCIENCE = 9
    SPORTS_AND_RECREATION = 10
    TECHNOLOGY = 11
    VISUAL_ARTS = 12
    WORLD_HISTORY = 13
