from enum import Enum

class Topics(Enum):

    ENTERTAINMENT_AND_POP_CULTURE = 1
    GEOGRAPHY_AND_TRAVEL = 2
    HEALTH_AND_MEDICINE = 3
    LIFESTYLES_AND_SOCIAL_ISSUES = 4
    LITERATURE = 5
    PHILOSOPHY_AND_RELIGION = 6
    POLITICS_LAW_AND_GOVERNMENT = 7
    SCIENCE = 8
    SPORTS_AND_RECREATION = 9
    TECHNOLOGY = 10
    VISUAL_ARTS = 11
    WORLD_HISTORY = 12
