name: App-Integration-Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unittest:
    name: Run application unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Install requirements
        run: pip install -r requirements.txt
        
      - name: Run unit tests
        run: make integration-tests
